const data = {
  user: {
    isAuth: true,
    profile: {
      emails: 'rb@anadeainc.com',
      displayName: 'Роман Бельский',
      lastName: 'Бельский',
      firstNameName: 'Роман',
      image:'https://lh6.googleusercontent.com/-Fy6px7pOvNM/AAAAAAAAAAI/AAAAAAAAAAA/AB6qoq3UdaIMShIJEFJiMFkRoa9o45eM9g/mo/photo.jpg?sz=50',
    },
  },
  searchCount: 42,
  pageCount: 20,
  currentPage: 2,
  selectedFilters: {
    specialization: [
      { name: '.NET', count: 0 },
      { name: 'Delphi', count: 0 },
      { name: 'DevOps', count: 0 },
      { name: 'Embedded', count: 0 },
      { name: 'SEO', count: 0 },
      { name: 'Support', count: 0 },
      { name: 'Technical Writer', count: 0 },
    ],
    level: [
      { name: 'Junior', count: 0 },
      { name: 'Middle', count: 0 },
    ],
    location: [
      { name: 'Днепр', count: 0 },
    ],
    status: [
      { name: 'Нанят', count: 0 },
    ],
    manager: [],
  },
  filters: {
    specialization: [
      { name: '.NET', count: 0 },
      { name: '1С', count: 0 },
      { name: 'Analyst', count: 0 },
      { name: 'Android', count: 0 },
      { name: 'Blockchain', count: 0 },
      { name: 'C++', count: 0 },
      { name: 'Data Science', count: 0 },
      { name: 'DBA', count: 0 },
      { name: 'Delphi', count: 0 },
      { name: 'DevOps', count: 0 },
      { name: 'Embedded', count: 0 },
      { name: 'ERP/CRM', count: 0 },
      { name: 'Flash/Flex', count: 0 },
      { name: 'FP', count: 0 },
      { name: 'Front End', count: 0 },
      { name: 'Golang', count: 0 },
      { name: 'HR', count: 0 },
      { name: 'iOS/macOS', count: 0 },
      { name: 'Java', count: 0 },
      { name: 'Node.js', count: 0 },
      { name: 'Other', count: 0 },
      { name: 'Perl', count: 0 },
      { name: 'PHP', count: 0 },
      { name: 'Product Manager', count: 0 },
      { name: 'Project Manager', count: 0 },
      { name: 'Python', count: 0 },
      { name: 'QA', count: 0 },
      { name: 'Ruby', count: 0 },
      { name: 'Sales', count: 0 },
      { name: 'Scala', count: 0 },
      { name: 'Security', count: 0 },
      { name: 'SEO', count: 0 },
      { name: 'Support', count: 0 },
      { name: 'Technical Writer', count: 0 },
      { name: 'Unity', count: 0 },
      { name: 'Дизайн', count: 0 },
      { name: 'Маркетинг', count: 0 },
      { name: 'Системный администратор', count: 0 },
    ],
    level: [
      { name: 'Trainee', count: 0 },
      { name: 'Junior', count: 0 },
      { name: 'Middle', count: 0 },
      { name: 'Senior', count: 0 },
      { name: 'Не указано', count: 0 },
    ],
    location: [
      { name: 'Гродно', count: 0 },
      { name: 'Минск', count: 0 },
      { name: 'Днепр', count: 0 },
      { name: 'Донецк', count: 0 },
      { name: 'Не указано', count: 0 },
    ],
    status: [
      { name: 'Нанят', count: 0 },
      { name: 'Уволен', count: 0 },
      { name: 'Не нанимать', count: 0 },
      { name: 'Резерв', count: 0 },
      { name: 'Тестовое', count: 0 },
      { name: 'Интерн', count: 0 },
      { name: 'Новый', count: 0 },
    ],
    manager: [
      { id: 0, url: '/static/img/user.jpg' },
      { id: 1, url: '/static/img/user.jpg' },
      { id: 2, url: '/static/img/user.jpg' },
      { id: 3, url: '/static/img/user.jpg' },
    ],
  },
  data: [
    {
      firstName: 'Roman',
      lastName: 'Belskiy',
      city: 'Ukraine, Dnipro',
      position: 'JS Developer',
      level: 'Senior',
      socialNetwork: 'linkedin',
      status: 'new',
      dateOfContact: '2018-04-26T07:52:54.437Z',
      managers: [
        {
          firstName: 'Vera',
          lastName: 'Glushkova',
          avatar: '/static/img/user.jpg',
        },
      ],
    },
    {
      firstName: 'Иван',
      lastName: 'Николаевич',
      city: 'Ukraine, Dnipro',
      position: 'Full-Stack Developer',
      level: 'Mega Senior',
      socialNetwork: 'github',
      status: 'interview',
      dateOfContact: '2018-04-26T07:52:54.437Z',
      managers: [
        {
          firstName: 'Vera',
          lastName: 'Glushkova',
          avatar: '/static/img/user.jpg',
        },
        {
          firstName: 'Vera',
          lastName: 'Glushkova',
          avatar: '/static/img/user.jpg',
        },
        {
          firstName: 'Vera',
          lastName: 'Glushkova',
          avatar: '/static/img/user.jpg',
        },
      ],
    },
  ],
};

export default data;
