export const CANDIDATES_FETCH_ALL = '@hr-portal/CANDIDATES/FETCH_ALL';
export const CANDIDATES_FETCH_ALL_SUCCESS = '@hr-portal/CANDIDATES/FETCH_ALL_SUCCESS';
export const CANDIDATES_FETCH_ALL_ERROR = '@hr-portal/CANDIDATES/FETCH_ALL_ERROR';
